[package]
name = "tpm2-protocol"
description = "TPM 2.0 protocol definitions"
version = "0.10.51"
license = "MIT OR Apache-2.0"
homepage = "https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/tpm2-protocol.git"
repository = "https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/tpm2-protocol.git"
authors = ["Jarkko Sakkinen <jarkko@kernel.org>"]
edition = "2021"
rust-version = "1.78"
readme = "README.md"

[dev-dependencies]

[dependencies]

[[test]]
name = "adhoc"
path = "tests/adhoc.rs"
harness = false

[[test]]
name = "message"
path = "tests/message.rs"
harness = false
