[package]
authors = ["Jarkko Sakkinen <jarkko@kernel.org>"]
description = "TPM 2.0 policy language interpreter"
edition = "2021"
homepage = "https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/tpm2-policy-language.git/about"
license = "MIT OR Apache-2.0"
name = "tpm2-policy-language"
readme = "README.md"
repository = "https://git.kernel.org/pub/scm/linux/kernel/git/jarkko/tpm2-policy-language.git"
rust-version = "1.81"
version = "0.9.5"

[dependencies]
hex = "0.4"
strum = { version = "0.26", features = ["derive"] }
thiserror = "1.0"
tpm2-crypto = "0.7.3"
tpm2-protocol = "0.15.8"
tpm2-vtpm = "0.3.4"

[dev-dependencies]
rstest = "0.21"
