.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright (c) 2025 Opinsys Oy
.\" Copyright (c) 2024-2025 Jarkko Sakkinen
.\"
.TH TPM2SH 1 "2025-10-15" "tpm2sh 0.11.4" "User Commands"
.SH NAME
tpm2sh \- a command-line tool for accessing TPM 2.0 devices
.SH SYNOPSIS
.B tpm2sh
[\fIOPTIONS\fR] \fICOMMAND\fR [\fICOMMAND-OPTIONS\fR] [\fIARGUMENTS\fR]...
.SH DESCRIPTION
.B tpm2sh
is a command-line tool for accessing TPM 2.0 devices.
.B tpm2sh
provides over-subscribed virtual memory manager for sharing key, sealed object
and session resources across multiple commands. It is the primary mechanism for
accessing transient TPM objects.
.P
The physical memory of a TPM chip is referenced with 'tpm:' tag, and virtual
memory with 'vtpm:' tag. E.g., 'tpm:81000001' references a persistent handle in
the physical memory.
.P
Virtual memory is based on caching TPM context objects, meaning that the cache
will automatically invalidate and reset on reboot. Therefore, it requires very
little management from the user.
.SH KEYS
.B tpm2sh 
provides 'convert' and 'load' subcommands for loading DER, or PEM
encoded internal and external keys. TPMKey ASN.1 format is the native output
format used by the subcommands when creating new TPM keys.
.P
.B tpm2sh
supports PKCS#1, PKCS#8 and SEC1 formats for external keys.

.SH BUGS
Please report bugs to the project's mailing list at tpm-protocol@lists.linux.dev.

.SH LICENSE
tpm2sh is licensed under the GPL-3.0-or-later.

.SH AUTHOR
Jarkko Sakkinen <jarkko@kernel.org>

.SH SEE ALSO
.BR openssl (1),
.BR credentials (7),
.BR keyrings (7)
