[package]
authors.workspace = true
description = "TPM 2.0 marshaler/unmarshaler"
edition.workspace = true
homepage.workspace = true
license = "MIT OR Apache-2.0"
name = "tpm2-protocol"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[test]]
name = "return_code"
path = "tests/return_code.rs"
harness = false

[[test]]
name = "message"
path = "tests/message.rs"
harness = false
