[package]
authors.workspace = true
description = "TPM 2.0 cryptographic routines"
edition.workspace = true
homepage.workspace = true
license = "MIT OR Apache-2.0"
name = "tpm2-crypto"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
openssl = { version = "0.10" }
strum = { version = "0.28", features = ["derive"] }
tpm2-protocol.workspace = true

[[test]]
name = "hmac"
path = "tests/hmac.rs"
harness = true

[[test]]
name = "public"
path = "tests/public.rs"
harness = true

[[test]]
name = "ecc"
path = "tests/ecc.rs"
harness = true

[[test]]
name = "kdf"
path = "tests/kdf.rs"
harness = true

[[test]]
name = "rsa"
path = "tests/rsa.rs"
harness = true

[dev-dependencies]
hex = "0.4"
rstest = "0.26"
